### ISSUE TITLE
Container starts but cannot connect to it

### ISSUE THREAD

**Issue by lockheed** [izer-xyz/3cx-docker#5]
I appreciate this is the only docker image I found for 3cx. We use it for our weekly call-in show as a non-profit NGO. 
We are using Ubuntu 20.04 server.

It was working fine for a time, but then in suddenly stopped. I tried recreating the container using the docker command you suggest, but it just would not start properly, falling into a reboot loop.

So I created it with docker-compose.yml like so:
```
version: '2'

services:

  voip:
    image: ghcr.io/izer-xyz/3cx:latest
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    tty: true # get systemd to log to console
    volumes:
      - /etc/localtime:/etc/localtime:ro # set time to the host time
      - tmp:/tmp # systemd 
      - run:/run # systemd
      - lock:/run/lock # systemd
      - voip:/mnt/voip # persistent storage
      - /sys/fs/cgroup:/sys/fs/cgroup:ro #systemd
    ports:
      - "5015:5015" # setup
      - "5090:5090"
      - "5090:5090/udp"

volumes:
  voip:
  tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  lock:
    driver_opts:
      type: tmpfs
      device: tmpfs
```

And now it starts and gets the IP from the docker bridge. However, it is not possible to connect to it on http:\\hostip:5015/?v=2 
All I get is "This site can’t be reached" even though the ports seem to be redirected from the host machine.

Do you have any suggestions?
